version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    networks:
      - carbon-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - carbon-network

volumes:
  mongo_data:

networks:
  carbon-network: